#!/bin/bash

# Raspberry Pi OS Kiosk Mode Setup
# Targets Raspberry Pi OS Bookworm with Wayland (labwc compositor)

set -e

AUTOSTART_DIR="$HOME/.config/labwc"
AUTOSTART_FILE="$AUTOSTART_DIR/autostart"
RC_FILE="$AUTOSTART_DIR/rc.xml"

echo "Fam Bam Dash - Kiosk Mode Setup"
echo "================================"
echo ""

# --- Preflight checks ---

if [ "$XDG_SESSION_TYPE" = "x11" ]; then
    echo "WARNING: This script is designed for Wayland (labwc)."
    echo "         Your current session appears to be X11."
    read -p "Continue anyway? [y/N]: " CONTINUE
    [[ "$CONTINUE" =~ ^[Yy]$ ]] || exit 1
    echo ""
fi

if ! command -v labwc &>/dev/null && [ ! -d "$AUTOSTART_DIR" ]; then
    echo "WARNING: labwc does not appear to be installed."
    echo "         Expected compositor for Raspberry Pi OS Bookworm with Wayland."
    read -p "Continue anyway? [y/N]: " CONTINUE
    [[ "$CONTINUE" =~ ^[Yy]$ ]] || exit 1
    echo ""
fi

# --- Prompt for URL ---

while true; do
    read -p "Enter the dashboard URL (e.g. http://192.168.1.100:12000): " KIOSK_URL
    if [ -n "$KIOSK_URL" ]; then
        break
    fi
    echo "URL cannot be empty. Please try again."
done

echo ""

# --- Install packages ---

echo "Installing required packages..."
sudo apt-get update -qq
# RPi OS may use 'chromium' or 'chromium-browser' depending on the release
if ! command -v chromium-browser &>/dev/null && ! command -v chromium &>/dev/null; then
    sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium
else
    echo "  chromium already installed, skipping."
fi

# Resolve the chromium binary name
if command -v chromium-browser &>/dev/null; then
    CHROMIUM_BIN="chromium-browser"
else
    CHROMIUM_BIN="chromium"
fi

echo ""

# --- Configure labwc autostart ---

echo "Configuring labwc autostart..."
mkdir -p "$AUTOSTART_DIR"

if [ -f "$AUTOSTART_FILE" ]; then
    cp "$AUTOSTART_FILE" "${AUTOSTART_FILE}.bak"
    echo "  Backed up existing autostart to ${AUTOSTART_FILE}.bak"
fi

cat > "$AUTOSTART_FILE" << EOF
# Fam Bam Dash Kiosk Mode — generated by kiosk-setup.sh

# Prevent display from blanking or sleeping
systemd-inhibit --what=idle:sleep:handle-lid-switch --who=kiosk --why="Kiosk mode" sleep infinity &

$CHROMIUM_BIN \\
  --noerrdialogs \\
  --disable-infobars \\
  --kiosk \\
  --ozone-platform=wayland \\
  --disable-features=TranslateUI \\
  --no-first-run \\
  --disable-restore-session-state \\
  --disable-session-crashed-bubble \\
  "$KIOSK_URL"
EOF

echo "  Wrote $AUTOSTART_FILE"

# --- Configure labwc rc.xml for cursor hiding ---

# Only touch rc.xml if it doesn't already exist (avoid overwriting user config)
if [ ! -f "$RC_FILE" ]; then
    cat > "$RC_FILE" << 'EOF'
<?xml version="1.0"?>
<openbox_config xmlns="http://openbox.org/3.4/rc">
  <core>
    <!-- Hide cursor after 1 second of inactivity -->
    <cursorTheme>none</cursorTheme>
    <font place="ActiveWindow">
      <name>sans</name>
      <size>10</size>
    </font>
  </core>
  <mouse>
    <dragThreshold>8</dragThreshold>
    <doubleClickTime>500</doubleClickTime>
    <screenEdgeWarpTime>400</screenEdgeWarpTime>
    <screenEdgeWarpMouse>false</screenEdgeWarpMouse>
  </mouse>
</openbox_config>
EOF
    echo "  Created $RC_FILE with cursor hiding"
else
    echo "  $RC_FILE already exists — skipping (edit manually to hide cursor)"
fi

# --- Disable RPi screen blanking via raspi-config if available ---

if command -v raspi-config &>/dev/null; then
    echo ""
    echo "Disabling screen blanking via raspi-config..."
    sudo raspi-config nonint do_blanking 1 2>/dev/null && echo "  Screen blanking disabled." \
        || echo "  Could not configure via raspi-config (non-fatal)."
fi

# --- Done ---

echo ""
echo "Kiosk mode configured successfully!"
echo ""
echo "The dashboard will open automatically on next login or reboot."
echo "  Autostart: $AUTOSTART_FILE"
echo ""
echo "To test without rebooting, run:"
echo "  $CHROMIUM_BIN --noerrdialogs --disable-infobars --kiosk --ozone-platform=wayland \"$KIOSK_URL\""
echo ""
echo "To change the URL later, edit: $AUTOSTART_FILE"
echo "To disable kiosk mode, delete: $AUTOSTART_FILE"
echo ""
read -p "Reboot now? [y/N]: " REBOOT
if [[ "$REBOOT" =~ ^[Yy]$ ]]; then
    sudo reboot
fi
